# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "rack-funky-cache"
  s.version = "0.0.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mika Tuupola"]
  s.date = "2012-10-15"
  s.description = "Funky caching for Rack based applications"
  s.email = "tuupola@appelsiini.net"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/rack/funky-cache.rb",
    "rack-funky-cache.gemspec",
    "test/rack_funky_cache_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "http://github.com/tuupola/rack-funky-cache"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "Funky caching for Rack based applications"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

